### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by sneerin** [bipbop/harlan#74]
/Users/user/workspace/harlan/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import prepackify from 'prepackify';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

**Comment by lfamorim** [comment]
@sneerin That occur mainly because you don't have the babel (https://babeljs.io/) dependencies installed, who are list as [dependencies](https://github.com/bipbop/harlan/blob/master/package.json#L21) at [package.json](https://github.com/bipbop/harlan/blob/master/package.json).

 Node.JS still not recognize ES2015 import statement. I recommend follow the documentation and run _npm install_ before _gulp build_.

If that don't solve your problem, please, reopen the issue.
